-- Create normalized search string for all uses
CREATE OR REPLACE FUNCTION osmetymology.toSearchString (text text) RETURNS text
	AS $$
		SELECT TRANSLATE(REGEXP_REPLACE(LOWER(text), '[^[:alnum:]]', '', 'gi'), 'áàâäãçéèêëíìîïñóòôöõúùûüýÿ', 'aaaaaceeeeiiiinooooouuuuyy')
	$$
	LANGUAGE SQL
	IMMUTABLE
	RETURNS NULL ON NULL INPUT;

-- Create aggregated table
DROP TABLE IF EXISTS osmetymology.ways_agg;
CREATE TABLE osmetymology.ways_agg (
	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name TEXT COLLATE "da_DK",
	searchname TEXT COLLATE "da_DK",
	geomtype TEXT COLLATE "da_DK",
	municipality_code varchar,
	object_ids BIGINT[],
	"name:etymology" TEXT COLLATE "da_DK",
	"name:etymology:wikipedia" TEXT COLLATE "da_DK",
	"name:etymology:wikidata" TEXT COLLATE "da_DK",
	geom GEOMETRY(Geometry, 4326)
);

-- Import points, ways, areas/polygons; intersect on municipality boundaries
INSERT INTO osmetymology.ways_agg (name, searchname, geomtype, municipality_code, object_ids, "name:etymology", "name:etymology:wikipedia", "name:etymology:wikidata", geom)
SELECT name, osmetymology.toSearchString(name), 'point', m.kode, array_agg(node_id), "name:etymology", "name:etymology:wikipedia","name:etymology:wikidata", ST_Intersection(st_transform(ST_COLLECT(geom), 4326), m.wkb_geometry)
FROM osmetymology.osm_points op
INNER JOIN osmetymology.municipalities m ON st_transform(op.geom,4326) && m.wkb_geometry AND ST_INTERSECTS(st_transform(op.geom,4326), m.wkb_geometry)
WHERE name IS NOT NULL AND ("name:etymology" IS NOT NULL OR "name:etymology:wikipedia" IS NOT NULL OR "name:etymology:wikidata" is not NULL)
GROUP by name, m.navn, m.kode, "name:etymology", "name:etymology:wikipedia","name:etymology:wikidata", m.wkb_geometry;

INSERT INTO osmetymology.ways_agg (name, searchname, geomtype, municipality_code, object_ids, "name:etymology", "name:etymology:wikipedia", "name:etymology:wikidata", geom)
SELECT name, osmetymology.toSearchString(name), 'line', m.kode, array_agg(way_id), "name:etymology", "name:etymology:wikipedia","name:etymology:wikidata", ST_Intersection(st_transform(ST_COLLECT(geom), 4326), m.wkb_geometry)
FROM osmetymology.osm_ways ow
INNER JOIN osmetymology.municipalities m ON st_transform(ow.geom,4326) && m.wkb_geometry AND ST_INTERSECTS(st_transform(ow.geom,4326), m.wkb_geometry)
WHERE name IS NOT NULL AND ("name:etymology" IS NOT NULL OR "name:etymology:wikipedia" IS NOT NULL OR "name:etymology:wikidata" is not NULL)
GROUP by name, m.navn, m.kode, "name:etymology", "name:etymology:wikipedia","name:etymology:wikidata", m.wkb_geometry;

INSERT INTO osmetymology.ways_agg (name, searchname, geomtype, municipality_code, object_ids, "name:etymology", "name:etymology:wikipedia", "name:etymology:wikidata", geom)
SELECT name, osmetymology.toSearchString(name), 'polygon', m.kode, array_agg(area_id), "name:etymology", "name:etymology:wikipedia","name:etymology:wikidata", ST_Intersection(st_transform(ST_UNION(geom), 4326), m.wkb_geometry)
FROM osmetymology.osm_polygons op
INNER JOIN osmetymology.municipalities m ON st_transform(op.geom,4326) && m.wkb_geometry AND ST_INTERSECTS(st_transform(op.geom,4326), m.wkb_geometry)
WHERE name IS NOT NULL AND ("name:etymology" IS NOT NULL OR "name:etymology:wikipedia" IS NOT NULL OR "name:etymology:wikidata" is not NULL)
GROUP by name, m.navn, m.kode, "name:etymology", "name:etymology:wikipedia","name:etymology:wikidata", m.wkb_geometry;

CREATE INDEX ways_agg_geom_idx ON osmetymology.ways_agg USING gist (geom);
CREATE INDEX ways_agg_name_idx ON osmetymology.ways_agg ("name" text_pattern_ops);
CREATE INDEX ways_agg_searchname_idx ON osmetymology.ways_agg ("searchname" text_pattern_ops);
CREATE INDEX ways_agg_municipality_idx ON osmetymology.ways_agg ("municipality_code");
CREATE INDEX ways_agg_name_etymology_wikidata_idx ON osmetymology.ways_agg ("name:etymology:wikidata");

DROP INDEX IF EXISTS osmetymology.municipalities_kode_idx;
CREATE INDEX municipalities_kode_idx ON osmetymology.municipalities ("kode");

-- Create stats table
DROP TABLE IF EXISTS osmetymology.stats;
CREATE TABLE osmetymology.stats (
	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	label TEXT COLLATE "da_DK",
	value INT
);

INSERT INTO osmetymology.stats (label, value) VALUES ('totalroads', (SELECT COUNT(*) FROM osmetymology.ways_agg) );
INSERT INTO osmetymology.stats (label, value) VALUES ('uniquenamedroads', (SELECT COUNT(DISTINCT name) FROM osmetymology.ways_agg) );
INSERT INTO osmetymology.stats (label, value) VALUES ('uniqueetymologywikidata', (SELECT COUNT(DISTINCT "name:etymology:wikidata") FROM osmetymology.ways_agg) );
INSERT INTO osmetymology.stats (label, value) VALUES ('localwikidataitems', (SELECT COUNT(*) FROM osmetymology.wikidata) );
INSERT INTO osmetymology.stats (label, value) VALUES ('importfinishtime', (SELECT EXTRACT(epoch from now())::INT) ); -- Should be file date for 'denmark-latest.osm.pbf'?