-- Shared aggregation setup used by both area and no-area modes.

-- :TODO: Fetch schema as variable or from external file

-- Create normalized search string for all uses
CREATE OR REPLACE FUNCTION toSearchString (text text) RETURNS text
	AS $$
		SELECT TRANSLATE(REGEXP_REPLACE(LOWER(text), '[^[:alnum:]]', '', 'gi'), 'áàâäãçéèêëíìîïñóòôöõúùûüýÿ', 'aaaaaceeeeiiiinooooouuuuyy')
	$$
	LANGUAGE SQL
	IMMUTABLE
	RETURNS NULL ON NULL INPUT;

-- Normalize featuretype from tags
CREATE OR REPLACE FUNCTION featureType (tags jsonb) RETURNS text
AS $$
	SELECT CASE
		WHEN tags->>'leisure' = 'park' THEN 'park'
		WHEN tags->>'tourism' = 'artwork' THEN 'artwork'
		WHEN tags->>'landuse' = 'cemetery' OR tags->>'amenity' = 'grave_yard' THEN 'cemetery'
		WHEN tags->>'amenity' = 'place_of_worship' THEN 'place_of_worship'
		WHEN tags->>'amenity' = 'prison' THEN 'prison'
		WHEN tags->>'office' IS NOT NULL THEN 'office'
		WHEN tags->>'place' = 'square' THEN 'square'
		WHEN tags->>'place' IN ('city','borough','suburb','quarter','neighbourhood','city_block','town','village','hamlet','islet') THEN 'place'
		WHEN tags->>'tourism' = 'museum' THEN 'museum'
		WHEN tags->>'highway' IS NOT NULL OR tags->>'footway' IS NOT NULL OR tags->>'cycleway' IS NOT NULL THEN 'way'
		WHEN tags->>'amenity' = 'parking' THEN 'parking'
		WHEN tags->>'sport' = 'equestrian' THEN 'equestrian'
		WHEN tags->>'amenity' IN ('school','college') THEN 'school'
		WHEN tags->>'amenity' = 'university' THEN 'university'
		WHEN tags->>'amenity' IN ('bar','pub','biergarten','nightclub','cafe') THEN 'alcohol'
		WHEN tags->>'man_made' = 'bridge' THEN 'bridge'
		WHEN tags->>'aeroway' IS NOT NULL THEN 'aeroway'
		WHEN tags->>'tourism' = 'zoo' THEN 'zoo'
		WHEN tags->>'amenity' = 'hospital' THEN 'hospital'
		WHEN tags->>'amenity' = 'kindergarten' THEN 'kindergarten'
		WHEN tags->>'power' IS NOT NULL THEN 'power'
		WHEN tags->>'tourism' = 'theme_park' THEN 'theme_park'
		WHEN tags->>'shop' = 'bakery' THEN 'bakery'
		WHEN tags->>'shop' IS NOT NULL THEN 'shop'
		WHEN tags->>'natural' = 'tree' OR tags->>'natural' = 'wood' OR tags->>'landuse' = 'forest' OR tags->>'leisure' = 'garden' THEN 'wood'
		WHEN tags->>'leisure' = 'sports_centre' THEN 'sport'
		WHEN tags->>'leisure' = 'playground' THEN 'playground'
		WHEN tags->>'amenity' = 'theatre' THEN 'theatre'
		WHEN tags->>'amenity' = 'cinema' THEN 'cinema'
		WHEN tags->>'amenity' = 'library' THEN 'library'
		WHEN tags->>'power' = 'substation' THEN 'power'
		WHEN tags->>'historic' = 'castle' THEN 'castle'
		WHEN tags->>'harbour' IS NOT NULL OR tags->>'water' = 'harbour' THEN 'harbour'
		WHEN tags->>'natural' IN ('water','bay') THEN 'water'
		WHEN tags->>'building' IS NOT NULL OR tags->>'building:part' IS NOT NULL THEN 'building'
		ELSE ''
	END
	AS featuretype
$$
LANGUAGE SQL
IMMUTABLE
RETURNS NULL ON NULL INPUT;

-- Helper function for grouping and merging json together
CREATE OR REPLACE FUNCTION jsonb_merge(a jsonb, b jsonb)
RETURNS jsonb LANGUAGE sql IMMUTABLE AS $$
    SELECT a || b;
$$;

CREATE OR REPLACE AGGREGATE jsonb_merge_agg(jsonb) (
    SFUNC = jsonb_merge,
    STYPE = jsonb,
    INITCOND = '{}'
);

-- Create gender helper table; normalize cisgender and transgender
DROP TABLE IF EXISTS gendermap;
CREATE TABLE gendermap (
	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	itemId TEXT,
	gender TEXT
);

INSERT INTO gendermap (itemId, gender)
VALUES ('Q6581072','female'), ('Q6581097','male'), ('Q1052281', 'female'), ('Q2449503', 'male'), ('Q15145779', 'female'), ('Q15145778', 'male');

-- Create aggregated table
DROP TABLE IF EXISTS locations_agg_next;
CREATE TABLE locations_agg_next (
	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name TEXT,
	searchname TEXT,
	geomtype TEXT,
	featuretype TEXT,
	area_code bigint,
	object_ids BIGINT[],
	"name:etymology" TEXT,
	"name:etymology:wikipedia" TEXT,
	"name:etymology:wikidata" TEXT,
	wikidatas TEXT[],
	geom GEOMETRY(Geometry, 4326),
	geom_dk GEOMETRY(Geometry, 25832)
);
